import { Employee } from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: '1',
    name: 'Anna Vantage',
    profession: 'CFO',
    department: 'Finance',
    skills: ['Financial Modeling', 'Risk Assessment', 'Budgeting'],
    avatarUrl: 'https://image.pollinations.ai/prompt/Young%20beautiful%20girl%20with%20long%20white%20hair,%2025%20years%20old,%20wearing%20a%20black%20suit,%20professional%20corporate%20portrait,%20futuristic,%20dark%20background?width=400&height=400&nologo=true',
    economicSwarm: 12500,
    timeWorked: 340,
    tasksCompleted: 142,
    incomeGenerated: 45000,
    voiceName: 'Kore',
    complianceMode: true,
    knowledgeBase: ['Tax Code 2026', 'Q1 Financials', 'Audit Guidelines'],
    budgetLimit: 50000,
  },
  {
    id: '2',
    name: 'Kira Vantage',
    profession: 'Marketing',
    department: 'Growth',
    skills: ['Campaign Strategy', 'SEO', 'Content Creation'],
    avatarUrl: 'https://picsum.photos/seed/kira/400/400',
    economicSwarm: 8400,
    timeWorked: 210,
    tasksCompleted: 89,
    incomeGenerated: 22000,
    voiceName: 'Puck',
    complianceMode: false,
    knowledgeBase: ['Brand Guidelines', 'Social Media Policy'],
    budgetLimit: 15000,
  },
  {
    id: '3',
    name: 'Lucy Vantage',
    profession: 'HR',
    department: 'Human Resources',
    skills: ['Recruitment', 'Employee Relations', 'Onboarding'],
    avatarUrl: 'https://picsum.photos/seed/lucy/400/400',
    economicSwarm: 5200,
    timeWorked: 180,
    tasksCompleted: 65,
    incomeGenerated: 0,
    voiceName: 'Charon',
    complianceMode: true,
    knowledgeBase: ['Labor Code', 'Internal Policies', 'Onboarding Manual'],
    budgetLimit: 10000,
  },
];
