import { Employee } from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: '1',
    name: 'Anna Vantage',
    profession: 'CFO',
    department: 'Finance',
    skills: ['Financial Modeling', 'Risk Assessment', 'Budgeting'],
    // Served from DSAAS/public via Vite static files.
    avatarUrl: '/anna/anna.mp4',
    economicSwarm: 12500,
    timeWorked: 340,
    tasksCompleted: 142,
    incomeGenerated: 45000,
    voiceName: 'Kore',
    complianceMode: true,
    knowledgeBase: ['Tax Code 2026', 'Q1 Financials', 'Audit Guidelines'],
    budgetLimit: 50000,
  },
  {
    id: '2',
    name: 'Kira Vantage',
    profession: 'Marketing',
    department: 'Growth',
    skills: ['Campaign Strategy', 'SEO', 'Content Creation'],
    avatarUrl: '/kira/kira.mp4',
    economicSwarm: 8400,
    timeWorked: 210,
    tasksCompleted: 89,
    incomeGenerated: 22000,
    voiceName: 'Puck',
    complianceMode: false,
    knowledgeBase: ['Brand Guidelines', 'Social Media Policy'],
    budgetLimit: 15000,
  },
  {
    id: '3',
    name: 'Mira Vantage',
    profession: 'Operations',
    department: 'Operations',
    skills: ['Process Optimization', 'Workflow Orchestration', 'Operational Analytics'],
    avatarUrl: '/mira/mira.mp4',
    economicSwarm: 6100,
    timeWorked: 190,
    tasksCompleted: 74,
    incomeGenerated: 14000,
    voiceName: 'Kore',
    complianceMode: false,
    knowledgeBase: ['Ops Playbook', 'SLA Guidelines', 'Runbook Templates'],
    budgetLimit: 12000,
  },
  {
    id: '4',
    name: 'Astra Vantage',
    profession: 'Product',
    department: 'Product',
    skills: ['Product Strategy', 'Requirements Engineering', 'Roadmap Planning'],
    avatarUrl: '/astra/astra.mp4',
    economicSwarm: 7400,
    timeWorked: 220,
    tasksCompleted: 92,
    incomeGenerated: 21000,
    voiceName: 'Puck',
    complianceMode: true,
    knowledgeBase: ['PRD Standards', 'Release Policy', 'Risk Register'],
    budgetLimit: 18000,
  },
  {
    id: '5',
    name: 'Asi Vantage',
    profession: 'Customer Support',
    department: 'Support',
    skills: ['Triage', 'Customer Communication', 'Escalation Handling'],
    avatarUrl: 'asi/asi.mp4',
    economicSwarm: 5200,
    timeWorked: 205,
    tasksCompleted: 88,
    incomeGenerated: 16500,
    voiceName: 'Charon',
    complianceMode: false,
    knowledgeBase: ['Support SOP', 'FAQ Library', 'Escalation Matrix'],
    budgetLimit: 15000,
  },
  {
    id: '66',
    name: 'Kiras Vantage',
    profession: 'Operations',
    department: 'Operations',
    skills: ['Process Optimization', 'Workflow Orchestration', 'Operational Analytics'],
    avatarUrl: '/ksera/Ksera_Digital_twin.mp4',
    economicSwarm: 6100,
    timeWorked: 190,
    tasksCompleted: 74,
    incomeGenerated: 14000,
    voiceName: 'Kore',
    complianceMode: false,
    knowledgeBase: ['Ops Playbook', 'SLA Guidelines', 'Runbook Templates'],
    budgetLimit: 12000,
  },
];
